#eksctl create cluster -f cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: techu-container-workshop
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-00f46cb95c600e80c }
      eu-west-1b: { id: subnet-05e55fa112acd2f3c }

nodeGroups:
  - name: workshop-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true