apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: resources
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app: resources
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: apps.local
      serviceName: resources